In [1]:
import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
%load_ext autoreload
%autoreload 2
import numpy as np
import hashlib
import time
import torch
from tqdm.notebook import tqdm
import sys
sys.path.append('../src')
from pow.compute.pipeline import Pipeline
from pow.compute.compute import AttentionModel, Compute


In [2]:
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [3]:
difficulty = 0
public_key = '1'
hidden_size = 5

In [4]:
a = np.arange(hidden_size)[:, None] @ np.arange(hidden_size)[None, :] + np.eye(hidden_size)
a = torch.FloatTensor(a) / hidden_size

In [5]:
device = torch.device('cpu')
pf = Compute('1', device, hid=hidden_size)
out = pf.forward(a)
h = pf.get_hash(out)

In [6]:

for d in ['cpu', 'cpu', 'cuda:0']:
    print(d)
    device = torch.device(d)
    pf = Compute('1', device, hid=hidden_size)
    out = pf.forward(a.to(device))
    h = pf.get_hash(out)
    print(out)
    print(h)

cpu
tensor([[-0.1125,  0.0034, -0.5369,  0.8934,  0.9922],
        [-0.0617,  0.2172, -0.5609,  1.0200,  0.9040],
        [ 0.0452,  0.5062, -0.5466,  1.0678,  0.7836],
        [ 0.0867,  0.5801, -0.5014,  1.0422,  0.7290],
        [ 0.1822,  0.9413, -0.5837,  1.0974,  0.6961]])
b"\xdb\xc2\x01\xf8\xb1\xcc23\xd0GS\x07{\xa9\x85\xb7['\xff=C\x0f\x1a\xea\x13\xec\xd1\x13\x86\x83[\x9f"
cpu
tensor([[-0.1125,  0.0034, -0.5369,  0.8934,  0.9922],
        [-0.0617,  0.2172, -0.5609,  1.0200,  0.9040],
        [ 0.0452,  0.5062, -0.5466,  1.0678,  0.7836],
        [ 0.0867,  0.5801, -0.5014,  1.0422,  0.7290],
        [ 0.1822,  0.9413, -0.5837,  1.0974,  0.6961]])
b"\xdb\xc2\x01\xf8\xb1\xcc23\xd0GS\x07{\xa9\x85\xb7['\xff=C\x0f\x1a\xea\x13\xec\xd1\x13\x86\x83[\x9f"
cuda:0
tensor([[-0.4681, -0.2761, -0.2445, -0.1581, -0.1612],
        [-0.4362, -0.2897, -0.3001, -0.1644, -0.0974],
        [-0.4608, -0.3109, -0.2901, -0.1928, -0.1291],
        [-0.5033, -0.3004, -0.3141, -0.1909, -0.1031],
        [